### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZenoX-TV** [Zolice/LilyGPT-discord#1]
Hello, I would like to report a bug that one of the files named `context.json` and `config.json` are not present
![sreenshot](https://user-images.githubusercontent.com/99297259/226130585-8e4faaca-3c32-4666-a342-794f80093e15.png)

**Comment by InfernoDragon0** [comment]
Hi there, seems like we've forgotten to auto generate those initial files, it shall be fixed in the next commit.

Thanks for reporting!

**Comment by InfernoDragon0** [comment]
fixed by commit 26b21aeacb231931408e137e8c45c28dac170b35
